-- Fake TX for the spectrum view. Development only; simulator only.
--
-- Loaded by elrs.lua's setMock(), which already gates on getVersion() returning
-- a "-simu" suffix (api_general.cpp:59-63 appends it only under #if defined(SIMU)),
-- so nothing here can execute on a real handset.
--
-- WHAT THIS IS FOR
-- TxSpectrumDecodeFrame() is unit tested, but the handset never runs it --
-- parseSpectrumMessage() in elrs.lua is a hand-rolled *second* decoder with no
-- test coverage of its own. This replays real encoder output (spectrumgolden.lua,
-- generated by gen_spectrumgolden.cpp) through the real click -> popup -> plot ->
-- exit path, which is the only place the two decoders are ever compared.
--
-- WHAT IT CANNOT PROVE
--   * Memory. The simulator uses plain desktop malloc and enforces no Lua limit
--     at all (CMakeLists.txt:573-575 returns before -DUSE_CUSTOM_ALLOCATOR).
--     Use mockup/heapchk.lua on a real radio instead.
--   * Anything below the wire: the CRSF router, the serial FIFO, the UART.
--   * Max-hold reset. ENTER's lcsClick is verified to go out with the right arg,
--     but the actual clear is TxSpectrumResetMaxHold() in firmware; there is no
--     firmware here, so the trace simply keeps replaying. That check is hardware.
--
-- Colour handsets cannot show this view by construction (setLCDvar leaves
-- SPEC_Y1 nil, and parseSpectrumMessage refuses to enter) -- run the Boxer or
-- another B&W profile.

local golden = loadScript("mockup/spectrumgolden.lua")
if golden == nil then return end
golden = golden()

-- Must match the Start Scan command field in elrsmock.lua. Filtering on it keeps
-- clicking Bind or Wifi Update from starting a fake sweep.
local SCAN_FIELD_ID = 28

-- getTime() is in 10ms ticks.
local FRAME_TICKS = 5 -- TX_SPECTRUM_EMIT_INTERVAL_MS 50: one frame per 50ms

-- The TX keeps sweeping until its reboot lands ~400ms after lcsCancel, so ~8
-- more frames arrive *after* the user hits RTN. Reproducing that is the whole
-- point of this delay: those in-flight frames are what re-opened the view that
-- had just been closed, before elrs.lua's fieldPopup entry guard existed.
local REBOOT_TICKS = 40

-- Two bands, streamed one at a time -- the cross-band Nomad model (DESIGN §10).
-- Band 1 = the 2.4GHz golden set, band 2 = the sub-GHz FCC915 set. The page button
-- (TX_SPECTRUM_LCS_NEXT_BAND = 8, see TxSpectrum.h) flips between them, which on a
-- real TX reconfigures the band-matched radio and restarts the sweep. Falls back to
-- the 2.4 set if an older spectrumgolden.lua without frames900 is on the card.
local bands = { golden.frames, golden.frames900 or golden.frames }
local curBand = 1

local streaming = false
local frameIdx = 0
local nextFrameAt = 0
local stopAt = nil

-- Intercept both directions. elrs.lua calls these as globals and never localises
-- them, so rebinding here is enough.
crossfireTelemetryPush = function(command, data)
  if command ~= 0x2D or data[3] ~= SCAN_FIELD_ID then return end
  local step = data[4]
  if step == 1 then       -- lcsClick: start a scan, or reset max-hold mid-scan
    streaming = true
    stopAt = nil
    nextFrameAt = 0
  elseif step == 8 then   -- TX_SPECTRUM_LCS_NEXT_BAND: page button flips the band
    curBand = (curBand == 1) and 2 or 1
    frameIdx = 0          -- the other band's sweep restarts cold, like the TX
    nextFrameAt = 0
  elseif step == 5 then   -- lcsCancel: TX reboots out of scan mode in ~400ms
    stopAt = getTime() + REBOOT_TICKS
  end
end

crossfireTelemetryPop = function()
  if not streaming then return end
  if stopAt ~= nil and getTime() > stopAt then
    streaming = false
    stopAt = nil
    return
  end
  -- Returning nil when no frame is due is required, not an optimisation:
  -- refreshNext() drains with "repeat ... until command == nil".
  local now = getTime()
  if now < nextFrameAt then return end
  nextFrameAt = now + FRAME_TICKS
  local frames = bands[curBand]
  frameIdx = (frameIdx % #frames) + 1
  return 0x30, frames[frameIdx]
end
