#!/usr/bin/env bash
#
# Build a BetaFPV SuperX Nano RX firmware image (ESP32-C3 + dual LR1121) and bake
# the board-specific hardware layout into it, so the result is a complete,
# ready-to-flash image -- NOT a "bare" one.
#
# This exists to prevent the exact mistakes we hit doing it by hand:
#   1. TX flags leaking in from super_defines.txt  -> wrong firmware.
#      This script writes a clean, isolated super_defines.txt for the build and
#      ALWAYS restores your original on exit (even on error).
#   2. Wrong MCU/radio target                       -> web UI rejects the image.
#      Pinned to the SuperX Nano's env (ESP32-C3 LR1121 RX).
#   3. "Bare" image with no hardware layout         -> no LED, dead radio.
#      binary_configurator bakes the SuperX Nano layout+overlay (LED on GPIO19,
#      dual-radio pins, RF-switch table, power tables, LNA gain).
#
# Output is flashable over USB (recommended, via the ELRS Configurator "UART"
# method or --flash below) or WiFi.
#
# Override any of these via environment variables:
#   FEATURE=RX_SPECTRUM_SCAN  ENV_NAME=... HW_TARGET=... DOMAIN=FCC_915 PHRASE=... OUT=...
# Examples:
#   ./build_superx_nano.sh                       # RX spectrum build, no baked phrase
#   PHRASE="my binding phrase" ./build_superx_nano.sh
#   FEATURE= ./build_superx_nano.sh              # STOCK build (no scanner) -- for recovery
#
set -euo pipefail

# ---- configuration (all overridable) ----
ENV_NAME="${ENV_NAME:-Unified_ESP32C3_LR1121_RX_via_UART}"  # pio env: C3 + LR1121 RX
HW_TARGET="${HW_TARGET:-betafpv.rx_dual.superx-nano}"       # targets.json path -> bakes layout+overlay
DOMAIN="${DOMAIN:-FCC_915}"                                 # sub-GHz regulatory (compile-time; US=FCC_915)
FEATURE="${FEATURE-RX_SPECTRUM_SCAN}"                       # empty string = stock build (no scanner)
EXTRA_DEFINES="${EXTRA_DEFINES:-}"                          # space-separated extra defines, no -D prefix (bench builds)
PHRASE="${PHRASE:-}"                                        # binding phrase; empty = keep stored/NVS bind (WiFi-friendly)
CFG_OPTS="${CFG_OPTS:-}"                                    # extra binary_configurator args, see the note below
VERIFY_OPTS="${VERIFY_OPTS:-}"                              # extra verify_image.py checks, e.g. --expect-domain 1
COMPARE_WITH="${COMPARE_WITH:-}"                            # a known-good image to diff the baked options against
REQUIRE_SYMBOLS="${REQUIRE_SYMBOLS:-}"                      # symbols that MUST be in the ELF, e.g. "RxSurveyArm"
OUT="${OUT:-firmware-superx-nano${FEATURE:+-rxspectrum}.bin}"

# ---- runtime options baked into the image, and why they are not optional ----
#
# binary_configurator writes ONE options blob, and options_LoadFromFlashOrFile()
# prefers the blob over anything in LittleFS whenever the flash-discriminator has
# changed -- which it does on every build, because it is random. So a setting
# omitted here is not "left as it was", it is reset to the firmware default on the
# next boot. Three of those defaults bite on a bench receiver:
#
#   --domain      MISSING MEANS AU915, NOT the compile-time Regulatory_Domain.
#                 FHSS.cpp indexes domains[] with firmwareOptions.domain, and
#                 `doc["domain"] | 0` is AU915 (20 ch, 915.5-926.9). A receiver
#                 built -DRegulatory_Domain_FCC_915 but flashed without --domain
#                 comes up on the wrong sub-GHz band and simply will not link.
#                 Harmless on SX128x, where domains[] has exactly one entry.
#   --auto-wifi   Missing disables the WiFi auto-start. That is the only way back
#                 into a receiver that will not link, so dropping it removes the
#                 recovery path exactly when a bench build is most likely to need it.
#   --phrase      Missing leaves the stored bind alone (CheckUpdateFlashedUid()
#                 returns early when !hasUID), so an already-bound receiver stays
#                 bound. Pass it anyway when you know the UID: it makes the image
#                 self-sufficient instead of dependent on what is already in NVS.
#
# Pass them per rig via CFG_OPTS, e.g.
#   CFG_OPTS="--domain fcc_915 --auto-wifi 60 --lock-on-first-connection"

cd "$(dirname "$0")"            # -> src/ (contains super_defines.txt, python/, hardware/)
SD="super_defines.txt"
BUILD_BIN=".pio/build/${ENV_NAME}/firmware.bin"

# ---- 1. isolate the build flags: swap in a clean super_defines, ALWAYS restore ----
BAK="$(mktemp)"
HAD_SD=0
if [ -f "$SD" ]; then cp "$SD" "$BAK"; HAD_SD=1; fi
restore() {
  if [ "$HAD_SD" -eq 1 ]; then cp "$BAK" "$SD"; else rm -f "$SD"; fi
  rm -f "$BAK"
}
trap restore EXIT

{
  echo "# AUTO-GENERATED by build_superx_nano.sh for this build only; your file is restored on exit."
  echo "-DRegulatory_Domain_${DOMAIN}"
  [ -n "$FEATURE" ] && echo "-D${FEATURE}"
  for d in $EXTRA_DEFINES; do echo "-D${d}"; done
} > "$SD"
echo ">> super_defines.txt for this build:"; sed 's/^/     /' "$SD"

# ---- 2. build the correct C3 LR1121 RX env ----
echo ">> building ${ENV_NAME} ..."
echo "" | pio run -e "$ENV_NAME"
[ -f "$BUILD_BIN" ] || { echo "ERROR: build produced no ${BUILD_BIN}"; exit 1; }

# ---- 2b. prove the feature actually linked, while the ELF still exists ----
#
# This has to happen HERE. PlatformIO deletes a target's build directory whenever
# the project checksum changes, and this script changes it twice by design (it
# swaps super_defines.txt in and restores it on exit) -- so the ELF is usually
# gone by the next pio invocation and the check cannot be repeated afterwards.
#
# `strings` cannot answer this: DBGLN is compiled out of a release build, so the
# image contains no feature names. The symbol table is the only evidence, and it
# matters because a define that fails to reach the compiler produces a perfectly
# green build with the feature silently absent -- which is exactly the flash you
# do not want to waste.
BUILD_ELF="${BUILD_BIN%.bin}.elf"
if [ -n "$REQUIRE_SYMBOLS" ] && [ -f "$BUILD_ELF" ]; then
  NM_BIN=""
  for c in "$HOME"/.platformio/packages/toolchain-*/bin/*-elf-nm*; do
    [ -x "$c" ] && "$c" "$BUILD_ELF" >/dev/null 2>&1 && { NM_BIN="$c"; break; }
  done
  if [ -z "$NM_BIN" ]; then
    echo "ERROR: no toolchain nm could read ${BUILD_ELF}; cannot confirm the feature linked"
    exit 1
  fi
  SYMS="$("$NM_BIN" "$BUILD_ELF")"
  for want in $REQUIRE_SYMBOLS; do
    line="$(echo "$SYMS" | grep -E "[[:space:]][A-Za-z][[:space:]].*${want}" | head -1)"
    [ -n "$line" ] || { echo "ERROR: '${want}' is NOT in ${BUILD_ELF} -- the feature did not compile in"; exit 1; }
    echo ">> linked: $line"
  done
fi

# ---- 3. bake the board layout (fixes bare-image / no-LED) + options ----
cp "$BUILD_BIN" "$OUT"
OUT_ABS="$(pwd)/${OUT}"
OUT_WIN="$(cygpath -w "$OUT_ABS" 2>/dev/null || echo "$OUT_ABS")"
CFG=(python python/binary_configurator.py --target "$HW_TARGET")
[ -n "$PHRASE" ] && CFG+=(--phrase "$PHRASE")
# shellcheck disable=SC2206  # deliberately word-split: CFG_OPTS is a flag list
[ -n "$CFG_OPTS" ] && CFG+=($CFG_OPTS)
CFG+=("$OUT_WIN")
echo ">> baking layout '${HW_TARGET}' into ${OUT} ..."
"${CFG[@]}"

# ---- 4. verify what actually ended up in the image ----
# Reads the blob back rather than grepping for a pin name: a bare image and one
# with the wrong regulatory domain both contain the string "led_rgb".
echo ""
VERIFY=(python python/verify_image.py "$OUT_WIN")
[ -n "$VERIFY_OPTS" ] && VERIFY+=($VERIFY_OPTS)
[ -n "$COMPARE_WITH" ] && VERIFY+=(--against "$COMPARE_WITH")
"${VERIFY[@]}" || { echo ""; echo "ERROR: ${OUT} failed verification, do NOT flash it"; exit 1; }

echo ""
echo "==================== DONE ===================="
echo " image   : ${OUT_ABS}"
echo " target  : ${HW_TARGET}   (layout baked: LED/RF-switch/power/pins set)"
echo " env     : ${ENV_NAME}"
echo " domain  : ${DOMAIN}     feature: ${FEATURE:-<stock>}     phrase: ${PHRASE:-<none/keep stored bind>}"
echo ""
echo " Flash over USB (recommended) with the ELRS Configurator (UART method),"
echo " or directly:"
echo "   python python/binary_configurator.py --target ${HW_TARGET} --flash uart --port <COM> \\"
echo "     ${PHRASE:+--phrase \"$PHRASE\" }\"${OUT_WIN}\""
echo " Or upload ${OUT} in the receiver's WiFi web UI."
echo "=============================================="
