#!/usr/bin/env bash
#
# Build a BetaFPV SuperX Nano RX firmware image (ESP32-C3 + dual LR1121) and bake
# the board-specific hardware layout into it, so the result is a complete,
# ready-to-flash image -- NOT a "bare" one.
#
# This exists to prevent the exact mistakes we hit doing it by hand:
#   1. TX flags leaking in from super_defines.txt  -> wrong firmware.
#      This script writes a clean, isolated super_defines.txt for the build and
#      ALWAYS restores your original on exit (even on error).
#   2. Wrong MCU/radio target                       -> web UI rejects the image.
#      Pinned to the SuperX Nano's env (ESP32-C3 LR1121 RX).
#   3. "Bare" image with no hardware layout         -> no LED, dead radio.
#      binary_configurator bakes the SuperX Nano layout+overlay (LED on GPIO19,
#      dual-radio pins, RF-switch table, power tables, LNA gain).
#
# Output is flashable over USB (recommended, via the ELRS Configurator "UART"
# method or --flash below) or WiFi.
#
# Override any of these via environment variables:
#   FEATURE=RX_SPECTRUM_SCAN  ENV_NAME=... HW_TARGET=... DOMAIN=FCC_915 PHRASE=... OUT=...
# Examples:
#   ./build_superx_nano.sh                       # RX spectrum build, no baked phrase
#   PHRASE="my binding phrase" ./build_superx_nano.sh
#   FEATURE= ./build_superx_nano.sh              # STOCK build (no scanner) -- for recovery
#
set -euo pipefail

# ---- configuration (all overridable) ----
ENV_NAME="${ENV_NAME:-Unified_ESP32C3_LR1121_RX_via_UART}"  # pio env: C3 + LR1121 RX
HW_TARGET="${HW_TARGET:-betafpv.rx_dual.superx-nano}"       # targets.json path -> bakes layout+overlay
DOMAIN="${DOMAIN:-FCC_915}"                                 # sub-GHz regulatory (compile-time; US=FCC_915)
FEATURE="${FEATURE-RX_SPECTRUM_SCAN}"                       # empty string = stock build (no scanner)
PHRASE="${PHRASE:-}"                                        # binding phrase; empty = keep stored/NVS bind (WiFi-friendly)
OUT="${OUT:-firmware-superx-nano${FEATURE:+-rxspectrum}.bin}"

cd "$(dirname "$0")"            # -> src/ (contains super_defines.txt, python/, hardware/)
SD="super_defines.txt"
BUILD_BIN=".pio/build/${ENV_NAME}/firmware.bin"

# ---- 1. isolate the build flags: swap in a clean super_defines, ALWAYS restore ----
BAK="$(mktemp)"
HAD_SD=0
if [ -f "$SD" ]; then cp "$SD" "$BAK"; HAD_SD=1; fi
restore() {
  if [ "$HAD_SD" -eq 1 ]; then cp "$BAK" "$SD"; else rm -f "$SD"; fi
  rm -f "$BAK"
}
trap restore EXIT

{
  echo "# AUTO-GENERATED by build_superx_nano.sh for this build only; your file is restored on exit."
  echo "-DRegulatory_Domain_${DOMAIN}"
  [ -n "$FEATURE" ] && echo "-D${FEATURE}"
} > "$SD"
echo ">> super_defines.txt for this build:"; sed 's/^/     /' "$SD"

# ---- 2. build the correct C3 LR1121 RX env ----
echo ">> building ${ENV_NAME} ..."
echo "" | pio run -e "$ENV_NAME"
[ -f "$BUILD_BIN" ] || { echo "ERROR: build produced no ${BUILD_BIN}"; exit 1; }

# ---- 3. bake the board layout (fixes bare-image / no-LED) + options ----
cp "$BUILD_BIN" "$OUT"
OUT_ABS="$(pwd)/${OUT}"
OUT_WIN="$(cygpath -w "$OUT_ABS" 2>/dev/null || echo "$OUT_ABS")"
CFG=(python python/binary_configurator.py --target "$HW_TARGET")
[ -n "$PHRASE" ] && CFG+=(--phrase "$PHRASE")
CFG+=("$OUT_WIN")
echo ">> baking layout '${HW_TARGET}' into ${OUT} ..."
"${CFG[@]}"

# ---- 4. sanity-check the layout actually embedded ----
if strings "$OUT" | grep -q "led_rgb"; then
  echo ">> layout embedded OK (found led_rgb pin -> LED will work)"
else
  echo ">> WARNING: could not confirm the layout embedded; inspect ${OUT} before flashing"
fi

echo ""
echo "==================== DONE ===================="
echo " image   : ${OUT_ABS}"
echo " target  : ${HW_TARGET}   (layout baked: LED/RF-switch/power/pins set)"
echo " env     : ${ENV_NAME}"
echo " domain  : ${DOMAIN}     feature: ${FEATURE:-<stock>}     phrase: ${PHRASE:-<none/keep stored bind>}"
echo ""
echo " Flash over USB (recommended) with the ELRS Configurator (UART method),"
echo " or directly:"
echo "   python python/binary_configurator.py --target ${HW_TARGET} --flash uart --port <COM> \\"
echo "     ${PHRASE:+--phrase \"$PHRASE\" }\"${OUT_WIN}\""
echo " Or upload ${OUT} in the receiver's WiFi web UI."
echo "=============================================="
